name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install cppunit
      run: sudo apt install nlohmann-json3-dev 
           sudo apt install libgtest-dev
           sudo apt install libssl-dev
           mkdir build
           cd build
           cmake ..
           cmake --build . -j
    - name: make
      run: make
    - name: make test
      run: make test
